version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=[PASSWORD]

  filesystem.api:
    image: ${DOCKER_REGISTRY-}filesystemapi
    build:
      context: .
      dockerfile: FileSystem.API/Dockerfile
    depends_on:
      - db
